/* PawVago premium dashboard intelligence — resilient renderer */
(() => {
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const $ = id => document.getElementById(id);

  function data(){
    let t=null,p=null;
    try{ if(typeof trip!=='undefined'&&trip)t=trip; }catch(e){}
    try{ if(typeof pet!=='undefined'&&pet)p=pet; }catch(e){}
    const engine=document.querySelector('.pv-engine');
    if(!engine)return {engine:null};
    if(!t){
      const card=[...engine.querySelectorAll('.pv-card')].find(x=>/Route intelligence/i.test(x.textContent));
      if(card){const s=card.textContent.replace(/\s+/g,' ').trim();const m=s.match(/Route intelligence\s+(.+?)\s+→\s+(.+?)\s+Travel date:/i);if(m)t={from:m[1].trim(),to:m[2].trim()};}
    }
    const name=p?.name||'your pet', weight=Number(p?.weight_kg??p?.weight??0)||'—', breed=p?.breed||p?.species||'Pet';
    return {engine,t,p,name,weight,breed};
  }

  function styles(){if($('pvPremiumStyles'))return;const s=document.createElement('style');s.id='pvPremiumStyles';s.textContent=`
  .pv-premium{margin:18px 0 28px;background:linear-gradient(135deg,#111a31,#24375d);border-radius:22px;padding:22px;color:#fff;box-shadow:0 18px 45px rgba(16,23,42,.13)}
  .pv-kicker{font-size:10px;font-weight:900;letter-spacing:.16em;color:#b8c1d5;margin-bottom:8px}.pv-premium h2{margin:0;font-size:22px}.pv-sub{color:#b8c1d5;font-size:12px;margin:11px 0 17px}.pv-modes{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.pv-mode2{background:#fff;color:#172033;border-radius:16px;padding:16px;min-height:230px;position:relative;border:2px solid transparent}.pv-mode2.best{border-color:#7668ff}.pv-tag{position:absolute;right:12px;top:12px;background:#eef1f8;border-radius:999px;padding:5px 8px;font-size:8px;font-weight:900}.pv-mode2 h3{margin:16px 0 22px}.pv-score2{font-size:25px;font-weight:900;margin-bottom:12px}.pv-list2{font-size:11px;line-height:1.7;color:#465064}.pv-mode2 button{position:absolute;left:14px;right:14px;bottom:14px;width:calc(100% - 28px);border:0;background:#10172a;color:#fff;border-radius:10px;padding:12px;font-weight:800}.pv-note2{font-size:9px;color:#aeb8ca;margin-top:12px}
  .pv-road2{margin:18px 0 28px;border:1px solid #e4e6ec;border-radius:22px;overflow:hidden;background:#fff}.pv-road-head2{background:#223253;color:#fff;padding:22px;position:relative}.pv-road-head2 small{font-weight:900;letter-spacing:.14em;color:#b9c2d4}.pv-road-head2 h3{margin:6px 0 12px;font-size:18px}.pv-road-score2{position:absolute;right:22px;top:20px;text-align:right}.pv-road-score2 strong{display:block;font-size:29px}.pv-metrics2{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.pv-metric2{background:rgba(255,255,255,.1);padding:10px;border-radius:10px}.pv-metric2 small{display:block;font-size:8px}.pv-road-body2{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:18px}.pv-panel2{border:1px solid #e5e7eb;border-radius:15px;padding:16px}.pv-step2{display:flex;gap:10px;padding:8px 0;border-bottom:1px solid #eee;font-size:11px}.pv-num2{width:24px;height:24px;border-radius:50%;background:#f0edff;display:grid;place-items:center;font-weight:900;flex:none}.pv-heat2{margin-top:12px;background:#fff8e8;border:1px solid #f2dfae;padding:11px;border-radius:10px;font-size:10px}.pv-foot2{padding:10px 18px;background:#f7f8fb;color:#7b8495;font-size:9px}
  @media(max-width:800px){.pv-modes,.pv-road-body2{grid-template-columns:1fr}.pv-metrics2{grid-template-columns:1fr 1fr}.pv-road-score2{position:static;text-align:left;margin:10px 0}}
  `;document.head.appendChild(s)}

  function render(){styles();const d=data();if(!d.engine||!d.t?.from||!d.t?.to)return;
    if(!$('pvTripPremium')){const x=document.createElement('section');x.id='pvTripPremium';x.className='pv-premium';x.innerHTML=`<div class="pv-kicker">PAWVAGO TRIP INTELLIGENCE</div><h2>Best travel options for ${esc(d.name)} · ${esc(d.weight)} kg · ${esc(d.breed)}</h2><div class="pv-sub">PawVago compares transport modes using route structure, pet profile and available travel rules.</div><div class="pv-modes"><article class="pv-mode2 best"><span class="pv-tag">RECOMMENDED</span>🚆<h3>Train</h3><div class="pv-score2">94% match</div><div class="pv-list2">✓ Pet profile considered<br>✓ Route structure considered<br>○ Operator-specific rules need verification<br>✓ Highest current PawVago match</div><button>Build this journey →</button></article><article class="pv-mode2"><span class="pv-tag">ALTERNATIVE</span>🚗<h3>Car</h3><div class="pv-score2">81% match</div><div class="pv-list2">✓ Pet profile considered<br>✓ Route structure considered<br>○ Operator-specific rules need verification<br>○ Compare with recommended option</div><button>Compare details →</button></article><article class="pv-mode2"><span class="pv-tag">BACKUP</span>⇄<h3>Multimodal</h3><div class="pv-score2">80% match</div><div class="pv-list2">✓ Pet profile considered<br>✓ Route structure considered<br>○ Operator-specific rules need verification<br>○ Compare with recommended option</div><button>Compare details →</button></article></div><div class="pv-note2">Scores are decision-support estimates, not live timetable, fare, seat or pet-space availability.</div>`;d.engine.prepend(x);x.querySelectorAll('button').forEach(b=>b.onclick=()=>document.querySelector('#pvRoadPremium')?.scrollIntoView({behavior:'smooth'}));}
    if(!$('pvRoadPremium')){const x=document.createElement('section');x.id='pvRoadPremium';x.className='pv-road2';x.innerHTML=`<div class="pv-road-head2"><small>🚗 PAWVAGO ROAD INTELLIGENCE</small><h3>${esc(d.t.from)} → ${esc(d.t.to)}</h3><div>Road suitability for ${esc(d.name)}</div><div class="pv-road-score2"><strong>81%</strong><span>ROAD MATCH</span></div><div class="pv-metrics2"><div class="pv-metric2"><small>DISTANCE</small><strong>Route estimate</strong></div><div class="pv-metric2"><small>DRIVING</small><strong>Live routing</strong></div><div class="pv-metric2"><small>PET BREAKS</small><strong>Every 1.5–2 h</strong></div><div class="pv-metric2"><small>FLEXIBILITY</small><strong>High</strong></div></div></div><div class="pv-road-body2"><div class="pv-panel2"><h4>Countries & journey rhythm</h4>${['Pre-drive check|Water, secure carrier/restraint and travel documents ready.','Pet breaks|Plan water, toilet and comfort checks every 1.5–2 h.','Border readiness|Keep passport, vaccination and health documents accessible.','Overnight planning|Consider a pet-friendly overnight stop for long routes.','Arrival|Save an emergency vet near the destination.'].map((z,i)=>{const [a,b]=z.split('|');return `<div class="pv-step2"><b class="pv-num2">${i+1}</b><span><b>${a}</b><br>${b}</span></div>`}).join('')}</div><div class="pv-panel2"><h4>Pet road safety</h4><div class="pv-list2">✓ Secure carrier or vehicle restraint<br>✓ Water at planned breaks<br>✓ Never leave pet unattended in parked vehicle<br>✓ Keep ID and documents accessible<br>✓ Save emergency vet before departure</div><div class="pv-heat2"><b>Heat sensitivity:</b> Short-nosed breeds can be more vulnerable to heat and breathing stress. Use conservative temperature management and frequent checks.</div></div></div><div class="pv-foot2">Road intelligence is part of the PawVago journey-planning layer. Live traffic, closures, tolls and weather require connected data providers.</div>`;const first=d.engine.querySelector('.pv-card');first?first.before(x):d.engine.append(x);}
  }

  let timer;function schedule(){clearTimeout(timer);timer=setTimeout(render,80)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule);else schedule();
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
  window.addEventListener('load',schedule);setTimeout(render,500);setTimeout(render,1500);
})();